# Generated by Django 4.0 on 2022-01-12 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_question_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
    ]
